### ISSUE TITLE
script install_yunohost.sh not available anymore

### ISSUE THREAD

**Issue by emiliien** [sylvainar/ansible-yunohost#2]
Hi ! 
Thxx for your work ! 
i would try to install ynh with ansible BUT i'm stuck on the download step ! 
is not really an issue with your code but ..... 
the link : "https://raw.githubusercontent.com/YunoHost/install_script/master/install_yunohost" is not available anymore.
may have you this script somewhere ? updated with the last version of the ynh installation ? 
Thx a lot.
Have good day .

EDIT : https://install.yunohost.org ...... but failed post install. 
EDIT 2: ok, arguments on my playbook where wrong ! so , juste change url of the script to the new one and everything 'll be ok =)

**Comment by sylvainar** [comment]
Can you give me the url you used so i can update the default value? 😄

**Comment by emiliien** [comment]
yep sure,
alors, https://install.yunohost.org  ;)
c'est à mon avis le même script que celui sur l'ancien lien.
Merci en tout cas.
C'est du bon taf !
Tu as également automatisé tes installs docker ? J'i vu sur le thread du
forum yunohost que tu avais migré sur des conteneurs .
utilises tu kubernetes ?
++



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le mar. 12 mai 2020 à 16:56, Sylvain Arnouts <notifications@github.com> a
écrit :

**Comment by sylvainar** [comment]
Merci, j'ai modifié la configuration du rôle.

En fait au final je n'utilisais plus les avantages de yunohost (pouvoir installer des applis rapidement), j'ai préféré switcher ma stack sur docker-compose. J'ai un repository perso où j'ai les docker-compose de tous mes projets, et j'utilise monit pour savoir si tout est bien en train de tourner et pour recevoir des notifications si un container est tombé.
Kubernetes est clairement overkill pour une installation à la maison, l'overhead généré par la partie gestion du cluster ne vaut pas le coup pour les 8 ou 10 containers que j'ai à faire tourner 😄

**Comment by emiliien** [comment]
Oui en effet !
Merci en tout cas.
bonne soirée.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le mar. 12 mai 2020 à 17:21, Sylvain Arnouts <notifications@github.com> a
écrit :
