### ISSUE TITLE
Certificate installation on a fresh install does not work as expected

### ISSUE THREAD

**Issue by rthouvenin** [sylvainar/ansible-yunohost#4]
When running the role on a fresh server, the task "Install certificates" does not actually install the certificates, because it expects that a diagnosis was run before. More over, the task is reported as OK, because the command returns exit code 0 even though it failed.

I've reported the wrong exit code here: https://github.com/YunoHost/issues/issues/1681

I think the role should be updated to accommodate this new expectation of the CLI, in one of these ways:

 - Add the option `--no-checks` to bypass the expectation
 - Add a task to run a diagnosis before installing the certificate (then even if the diagnosis result is not perfect, `cert-install` will accept to run as long as the domains have a valid DNS record)

I'm happy to PR the change, but I'm not sure which option makes most sense :)

**Comment by sylvainar** [comment]
Hey, thanks for your issue. I'd try option 2 but would go back to option 1 if too fastidious :smile: 
Feel free to make a PR when you're done :+1:

**Comment by sylvainar** [comment]
Fixed on #5
